### ISSUE TITLE
faker.internet.uuid not returning uuid

### ISSUE THREAD

**Issue by Smudge3806** [REBELinBLUE/Paw-FakerDynamicValue#3]
Installed your plugin today and the `uuid` function does not appear to be returning anything.

`Paw/3.1.6 (Macintosh; OS X/10.13.4)`

**Comment by REBELinBLUE** [comment]
Hmm, weird, that is the one I use the most

**Comment by REBELinBLUE** [comment]
Could you send me a screenshot of how you are using it as it appears to be working for me?

![screen shot 2018-05-03 at 15 49 29](https://user-images.githubusercontent.com/2143908/39584136-97ac0ce2-4ee9-11e8-9dfc-a0760a0d617d.png)

**Comment by Smudge3806** [comment]
Yeah, is it affected by Language? I have it set to "English"

**Comment by Smudge3806** [comment]
Found the issue, the documentation says the Category is Internet however switching it to Random Data fixes the issue!

**Comment by REBELinBLUE** [comment]
I am using English as well, however I wonder if it is the do with the OS X version (seems odd that it would be) but I have an old version at work, I will check on my own Mac when I get home

-----------------
Stephen Ball
stephen@rebelinblue.com

**Comment by REBELinBLUE** [comment]
Ah that is interesting, I wondering if they have changed the category it is under since I wrote it. I shall update the source and check

-----------------
Stephen Ball
stephen@rebelinblue.com

**Comment by REBELinBLUE** [comment]
Which documentation are you looking at? The README https://github.com/Marak/faker.js/blob/master/Readme.md still lists it under random?

**Comment by Smudge3806** [comment]
Yours, I know it was probably for example but I was being lazy :)

https://github.com/REBELinBLUE/Paw-FakerDynamicValue/blob/master/README.md

**Comment by Smudge3806** [comment]
Thanks for your time on this and sorry for sending you on a wild goose chase...

**Comment by REBELinBLUE** [comment]
Ha ha, oops! Sorry I'll get that fixed
